config/routes.rb
Rails.application.routes.draw do
  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(allowed_params)
    @blog.save
    redirect_to blogs_path
  end

  private

  def allowed_params
    params.require(:blog).permit(:title, :body, :user_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/index.html.erb
<%= link_to "Create Blog", new_blog_path %>

<% @blogs.each do |blog| %>
  <h3><%= blog.title %></h3>
  <article><%= blog.body %></article>
  <author><%= blog.user_name %></author>
  <time><%= blog.created_at %></time>
<% end %>

app/views/blogs/new.html.erb
<%= form_for @blog do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br><%= f.label :body %>
  <%= f.text_field :body %>
  <br><%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <br><%= f.submit "Save Blog" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>